export type Kind = 'build'|'weapon'|'ash'|'talisman'|'spell'|'boss'|'guide';
export type Stat = 'VIG'|'MND'|'END'|'STR'|'DEX'|'INT'|'FTH'|'ARC';
export type Stats = Record<Stat,number>;
export type Section = {title:string; paragraphs:string[]};
export type Source = {label:string;url:string};
export type Loadout = {id:string; role:string;note:string};
export type Build = {className:keyof typeof classes;level:number;stats:Stats;core:Stat[];loadout:Loadout[];armor:string;flasks:string;progression:{stage:string;text:string}[];alternatives:string[];encounters:string[]};
export type RecordNode = {id:string;name:string;kind:Kind;category:string;summary:string;dlc:boolean;art:string;tags:string[];facts?:[string,string][];requirements?:Partial<Stats>;sections:Section[];related:string[];sources:Source[];build?:Build};
export const PATCH='1.17';
export const SOURCE_DATE='2026-10-04';
export const patchSource:Source={label:'Bandai Namco: patch 1.17 (27 August 2026)',url:'https://en.bandainamcoent.eu/elden-ring/news/elden-ring-patch-notes-version-117'};
export const classes={
  Vagabond:{level:9,stats:{VIG:15,MND:10,END:11,STR:14,DEX:13,INT:9,FTH:9,ARC:7}},
  Samurai:{level:9,stats:{VIG:12,MND:11,END:13,STR:12,DEX:15,INT:9,FTH:8,ARC:8}},
  Astrologer:{level:6,stats:{VIG:9,MND:15,END:9,STR:8,DEX:12,INT:16,FTH:7,ARC:9}},
  Confessor:{level:10,stats:{VIG:10,MND:13,END:10,STR:12,DEX:12,INT:9,FTH:14,ARC:9}},
  Bandit:{level:5,stats:{VIG:10,MND:11,END:10,STR:9,DEX:13,INT:9,FTH:8,ARC:14}},
} as const;
export const stats:Stat[]=['VIG','MND','END','STR','DEX','INT','FTH','ARC'];
export const statNames:Record<Stat,string>={VIG:'Vigor',MND:'Mind',END:'Endurance',STR:'Strength',DEX:'Dexterity',INT:'Intelligence',FTH:'Faith',ARC:'Arcane'};
export const kindLabels:Record<Kind,string>={build:'PvE build',weapon:'Armament',ash:'Ash of War',talisman:'Talisman',spell:'Spell',boss:'Boss',guide:'Field guide'};
export const wiki=(title:string):Source=>({label:`Eldenpedia: ${title}`,url:`https://eldenring.wiki.gg/wiki/${encodeURIComponent(title.replaceAll(' ','_'))}`});
const section=(title:string,...paragraphs:string[]):Section=>({title,paragraphs});
const base=(id:string,name:string,kind:Kind,category:string,summary:string,art:string,dlc=false)=>({id,name,kind,category,summary,art,dlc,tags:[category]});

export const builds:RecordNode[]=[
  {...base('colossal-knight','Colossal Knight','build','Strength','Heavy steel, measured trades, and a stance break you can actually punish.','greatsword'),tags:['Strength','Melee','Stance'],
    build:{className:'Vagabond',level:150,stats:{VIG:60,MND:16,END:37,STR:78,DEX:13,INT:9,FTH:9,ARC:7},core:['STR'],
      loadout:[{id:'greatsword',role:'Main hand',note:'Heavy affinity, +25. Two-hand for the regular moveset; all requirements also work one-handed.'},{id:'lions-claw',role:'Skill',note:'Use once in a confirmed opening. Hyperarmor is permission to finish an attack, not protection from damage.'},{id:'axe-talisman',role:'Charged attacks',note:'For fully charged heavy attacks; swap when you use mostly skills.'},{id:'shard-of-alexander',role:'Skill damage',note:'Late quest reward. The build works without it.'},{id:'green-turtle',role:'Stamina recovery',note:'Lower your guard between attacks.'},{id:'dragoncrest-greatshield',role:'Physical defense',note:'Late game. Use a weaker Dragoncrest Shield variant before Elphael.'}],
      armor:'Start with the Vagabond set. Later use pieces of the Knight set from Roundtable Hold; mix lighter gloves or helmet as needed. Keep total equipped weight strictly below 70% of your current maximum. The sword alone weighs 23.0; a second weapon or shield counts even when put away.',
      flasks:'Begin near 10 Crimson / 4 Cerulean at 14 charges; move one charge toward Crimson if you rarely use Lion’s Claw. Physick: Strength-knot early, then Stonebarb Cracked Tear for a short stance-pressure window and Opaline Hardtear for defense. These are optional, not requirements.',
      progression:[{stage:'Early · Limgrave / RL 20–40',text:'Use the starting Longsword or buy a Zweihander on the Weeping Peninsula. Raise Vigor toward 30 first. Greatsword needs 21 Strength and 12 Dexterity when two-handed, or 31 Strength one-handed. Ride to the Caelid carriage and leave rather than fighting the dogs.'},{stage:'Middle · Liurnia / Altus / RL 60–90',text:'Collect the Iron Whetblade in Stormveil for Heavy options, then defeat the lion in Fort Gael for Lion’s Claw. Keep upgrading one normal weapon. Aim for Vigor 40, enough Endurance for medium load, and Strength around 40 before pushing damage stats.'},{stage:'Late · RL 120–150',text:'Finish Vigor 60 and Strength 78, then Endurance and Mind as shown. Upgrade Greatsword to +25 when an Ancient Dragon Smithing Stone is available. Complete Alexander’s quest for his shard. Your roll matters more than wearing the heaviest set.'}],
      alternatives:['Keep the lighter Zweihander if Greatsword forces a heavy roll; it needs 19 STR / 11 DEX one-handed.','Use the sword’s crouching or rolling thrust in short openings; you do not need Lion’s Claw for every punish.','For very high physical resistance, a separately upgraded strike weapon can help; do not expect Heavy affinity to change a sword into strike damage.'],encounters:['margit','radahn','radagon-elden-beast']},
    sections:[section('Fight with a reserve','Wait for a combo to end, step into range, and choose one jump heavy or one Lion’s Claw. Keep stamina for the escape. A second heavy attack is a decision based on the recovery animation, not a fixed rotation.','A stance break creates a critical opportunity. Stop swinging, approach the correct side, and use a light attack when the critical position is available. Charged attacks cost time: shorten the charge if the boss starts moving.'),section('Where it struggles','Long recovery punishes you against quick enemies and multi-part combos. Learn the fight with single light attacks before adding a skill. Physical damage remains useful against bleed-immune targets, but stance breaks do not cancel every scripted transition.','This is a base-game build. No DLC talisman, Great Rune, stat-boosting armor, multiplayer trade or temporary buff is included in the level calculation.')],
    related:['greatsword','lions-claw','affinities','stance-and-survival','first-route'],sources:[wiki('Greatsword'),wiki("Skill: Lion’s Claw".replace('’',"'")),wiki('Strength'),wiki('Vagabond')]},
  {...base('bloodhound-ranger','Bloodhound Ranger','build','Dexterity','An early curved greatsword that stays useful long after Limgrave.','curved'),tags:['Dexterity','Melee','Bleed'],
    build:{className:'Samurai',level:150,stats:{VIG:60,MND:20,END:30,STR:30,DEX:64,INT:9,FTH:8,ARC:8},core:['DEX','STR'],
      loadout:[{id:'bloodhounds-fang',role:'Main hand',note:'Somber +10. Fixed Bloodhound’s Finesse; no affinity change.'},{id:'brass-shield',role:'Optional off hand',note:'No Skill lets the right-hand skill take priority. Put it away and two-hand when you want more Strength contribution.'},{id:'claw-talisman',role:'Jump attacks',note:'Boosts ordinary jump attacks, not the skill because it happens to jump.'},{id:'shard-of-alexander',role:'Skill damage',note:'Optional late reward.'},{id:'green-turtle',role:'Recovery',note:'A useful early slot for long fights.'},{id:'dragoncrest-greatshield',role:'Defense',note:'Use an earlier Dragoncrest variant until Elphael.'}],
      armor:'Land of Reeds is a practical starting point. Add Knight pieces if they fit below 70% equipment load. Include the 11.5-weight sword and optional 7.0-weight shield in that check.',
      flasks:'Try 11 Crimson / 3 Cerulean with 14 total charges. Use Dexterity-knot early and Opaline Hardtear for a safer learning run; a stamina-oriented tear is a reasonable alternative. No spell buff is required.',
      progression:[{stage:'Early · RL 20–40',text:'Use the starting Uchigatana until 17 Dexterity and at least 12 Strength for two-handed Fang. Defeat Darriwil in Forlorn Hound Evergaol; Blaidd can help after his Mistwood meeting. Reach 18 Strength for one-handed use. Bring Vigor toward 30.'},{stage:'Middle · RL 60–90',text:'Buy early Somber stones from Iji and explore mines for later tiers. Vigor 40, Dexterity 35–40 and enough Endurance for medium load are more useful than rushing to the final damage spread. Learn both inputs of Finesse separately.'},{stage:'Late · RL 120–150',text:'Settle at the listed 30 STR / 64 DEX split, Vigor 60, and Somber +10. Finish Alexander’s quest if you want to emphasize Finesse. Use jumping attacks and single swings when a boss leaves too little time for the full skill.'}],
      alternatives:['Keen Uchigatana +25 with Unsheathe gives faster, shorter recovery at less weight.','Bloodflame Blade is optional only after changing the spread to meet 12 FTH / 10 ARC and equipping a seal; the published 150 spread cannot cast it.','Against bleed immunity, retain Fang’s direct physical damage and stop chasing a hemorrhage proc. Arcane does not increase its bleed buildup because Fang has no Arcane scaling.'],encounters:['margit','radahn','malenia']},
    sections:[section('Two inputs, two decisions','Bloodhound’s Finesse starts with a slash and retreat. Its heavy follow-up closes distance. Check what the enemy is doing before taking that follow-up; committing into the next combo undoes the benefit of the retreat.','A jump heavy is often the simpler answer when a boss finishes a slow overhead attack. With a shield, block a single manageable hit and guard counter only after the chain ends. Let stamina refill with the shield lowered.'),section('The limitations','Bleed is extra damage, not the build’s only plan. Fang’s innate buildup does not justify spending points on Arcane. Wet conditions and enemy resistances can matter if you add a fire buff later.','Avoid backing yourself toward an arena wall: the retreating skill needs space. The current build has no incantations and no Shadow of the Erdtree dependencies.')],related:['bloodhounds-fang','uchigatana','claw-talisman','stance-and-survival'],sources:[wiki("Bloodhound's Fang"),wiki('Claw Talisman'),wiki('Samurai')]},
  {...base('carian-spellblade','Carian Spellblade','build','Intelligence','Sorcery at range, Moonveil at close quarters, and a physical answer for magic resistance.','staff'),tags:['Intelligence','Sorcery','Hybrid'],
    build:{className:'Astrologer',level:150,stats:{VIG:55,MND:30,END:20,STR:12,DEX:18,INT:78,FTH:7,ARC:9},core:['INT'],
      loadout:[{id:'moonveil',role:'Main hand',note:'Somber +10; fixed Transient Moonlight.'},{id:'carian-regal-scepter',role:'Off-hand catalyst',note:'Somber +10, requires 60 INT. Use the starting Astrologer’s Staff before that.'},{id:'carian-slicer',role:'Fast melee spell',note:'Use for short openings or conserving FP compared with larger spells.'},{id:'rock-sling',role:'Physical ranged spell',note:'An option against magic resistance; allow room for the rocks to travel.'},{id:'shard-of-alexander',role:'Skill slot',note:'Only improves Moonveil’s skill, not sorceries.'},{id:'green-turtle',role:'Recovery slot',note:'Helps movement between casts.'},{id:'dragoncrest-greatshield',role:'Defense slot',note:'Earlier variants are fine.'}],
      armor:'Astrologer or light Knight pieces, with a medium roll. Avoid relying on an Intelligence crown to meet staff requirements: the listed spread meets them unaided. Vigor 55 is the compromise that leaves room for both melee requirements and casting resources.',
      flasks:'Start with 8 Crimson / 6 Cerulean at 14 charges, then adapt to how often you cast. Magic-Shrouding Cracked Tear favors magic damage; pair it with Opaline Hardtear for defense. Rock Sling deals physical damage and does not benefit from the magic tear.',
      progression:[{stage:'Early · RL 20–40',text:'Raise Vigor to 25–30, keep the starting staff upgraded, and buy useful spells rather than pushing Intelligence alone. Sellen sells Carian Slicer after receiving the Royal House Scroll. Rock Sling and Meteorite Staff can be collected in the Street of Sages Ruins, but the Caelid detour is dangerous.'},{stage:'Middle · RL 60–90',text:'Acquire Moonveil from the Magma Wyrm in Gael Tunnel once you can handle the fight. Meet 12 STR / 18 DEX / 23 INT before using it. Defeat Rennala and exchange her remembrance for Carian Regal Scepter, then keep it stored until 60 INT.'},{stage:'Late · RL 120–150',text:'Build toward 78 Intelligence, 30 Mind and 55 Vigor. Upgrade Moonveil and the scepter independently with Somber stones. Finish Alexander only if the skill is a major part of your play. Allocate another spell slot to a ranged magic projectile you already own.'}],
      alternatives:['Keep a leveled normal sword on Magic affinity if you have not beaten the Gael Tunnel boss.','Against magic-resistant Rennala, use Rock Sling and physical melee; repeatedly casting blue projectiles is inefficient.','A sorcery-first variant can remove Moonveil’s STR/DEX investment through rebirth, but it is a different spread. This version preserves a reliable close-range tool.'],encounters:['rennala','radahn','malenia']},
    sections:[section('Change the tool, not just the distance','Cast from a position with a retreat route. Carian Slicer is for the moment an enemy closes in; Moonveil’s heavy skill follow-up is for a wider opening. You do not need to roll away until the arena runs out of space.','Rock Sling has slow travel and can clip scenery. Keep a clean line of sight and expect some agile bosses to evade the rocks. A physical damage type is useful against magic resistance, but does not make casting safe during every attack.'),section('Resource limits','Casting and dodging share stamina. Leave enough to dodge after the spell, and drink Cerulean only in a known recovery window. This build cannot cast Faith or Arcane incantations.','Transient Moonlight has changed across patches; this archive does not promise older stance-damage or one-combo kill claims. No simulated or measured DPS ranking is provided.')],related:['moonveil','carian-regal-scepter','carian-slicer','rock-sling','upgrades-and-rebirth'],sources:[wiki('Moonveil'),wiki('Carian Regal Scepter'),wiki('Carian Slicer'),wiki('Rock Sling'),wiki('Astrologer')]},
  {...base('blasphemous-pilgrim','Blasphemous Pilgrim','build','Faith','Fire, healing on skill hits, and a lightning option when flame is the wrong answer.','flame'),tags:['Faith','Incantation','Hybrid'],
    build:{className:'Confessor',level:150,stats:{VIG:60,MND:25,END:25,STR:22,DEX:15,INT:9,FTH:64,ARC:9},core:['FTH'],
      loadout:[{id:'blasphemous-blade',role:'Main hand',note:'Somber +10; Taker’s Flames is fixed.'},{id:'finger-seal',role:'Catalyst',note:'Normal +25; an accessible seal that meets this build’s requirements.'},{id:'lightning-spear',role:'Ranged alternative',note:'Lightning damage when fire is resisted.'},{id:'golden-vow',role:'Aura buff',note:'Cast before the fog when safe; keep resources for fighting.'},{id:'flame-grant-me-strength',role:'Body buff',note:'Boosts physical and fire damage, not Lightning Spear.'},{id:'shard-of-alexander',role:'Skill slot',note:'Optional late reward.'},{id:'green-turtle',role:'Recovery slot',note:'Available early.'},{id:'dragoncrest-greatshield',role:'Defense slot',note:'Physical defense for learning the fight.'}],
      armor:'Use the Confessor set initially and mix Knight pieces later. With the 13.5-weight sword, stay under 70% load. This setup leaves one talisman slot open for an encounter-specific resistance talisman rather than forcing four damage bonuses.',
      flasks:'Try 9 Crimson / 5 Cerulean at 14 charges. Flame-Shrouding Cracked Tear supports the sword skill; Opaline Hardtear supports survival. Shift toward Cerulean only if the skill’s healing is consistently landing.',
      progression:[{stage:'Early · RL 20–40',text:'Use the starting Broadsword and Finger Seal. Prioritize Vigor and upgrade the weapon. Flame, Grant Me Strength is behind Fort Gael; it is optional while learning. Do not treat Blasphemous Blade as a starting weapon.'},{stage:'Middle · RL 60–100',text:'Acquire Lightning Spear from the Dragon Cult Prayerbook knight south of Artist’s Shack in Liurnia. Explore Volcano Manor, finish desired manor contracts before Rykard, then defeat him and trade his remembrance for the blade. Meet 22 STR / 15 DEX / 21 FTH.'},{stage:'Late · RL 120–150',text:'Bring Faith to 64 and Vigor to 60 while keeping 25 Mind and Endurance. Obtain Golden Vow at Corpse-Stench Shack in Mt. Gelmir. Keep the seal upgraded and change your damage type for resistant enemies.'}],
      alternatives:['A normal sword on Flame Art affinity is a base-game Faith weapon before Rykard. Fire affinity is a different option that favors Strength.','A higher-Faith build can compare the Erdtree Seal at 40+ FTH; this catalogue keeps the accessible Finger Seal and does not claim it has the highest scaling at every level.','Use Lightning Spear against fire-resistant targets. Flame, Grant Me Strength does not buff lightning; do not spend FP refreshing it for that purpose.'],encounters:['malenia','radagon-elden-beast','messmer']},
    sections:[section('Healing still needs a hit','Taker’s Flames restores HP when its flame connects, so cast through a clear lane. The windup is long enough to get punished. Use it after a committed boss recovery or against a group approaching in a line.','Golden Vow and Flame, Grant Me Strength occupy different buff categories and can coexist. Cast the longer aura buff first, then the short body buff, and enter. Reapplying during combat is optional; a safe dodge is better than taking damage while refreshing.'),section('What this build cannot do','Fire resistance is a real limit, especially for Messmer. Switch to lightning incantations and avoid assuming the sword is universally best. Lightning Spear needs a spell opening, too.','Taker’s Flames no longer has its old knockdown behavior after patch 1.12. It is not a guarantee that Malenia will remain on the ground. No DLC equipment is required even when taking this build into the expansion.')],related:['blasphemous-blade','finger-seal','lightning-spear','golden-vow','flame-grant-me-strength','affinities'],sources:[wiki('Blasphemous Blade'),wiki("Unique Skill: Taker's Flames"),wiki('Golden Vow'),wiki('Flame, Grant Me Strength'),wiki('Confessor')]},
  {...base('dragonblood-duelist','Dragonblood Duelist','build','Arcane','Twinblade pressure with an Occult fallback for enemies that refuse to bleed.','twinblade'),tags:['Arcane','Bleed','Dragon Communion'],
    build:{className:'Bandit',level:150,stats:{VIG:60,MND:20,END:25,STR:12,DEX:30,INT:9,FTH:15,ARC:58},core:['ARC','DEX'],
      loadout:[{id:'eleonoras-poleblade',role:'Main weapon',note:'Somber +10; fixed physical/fire damage and Bloodblade Dance.'},{id:'uchigatana',role:'Alternative weapon',note:'Occult +25 with Unsheathe, after acquiring the Black Whetblade. A physical-damage alternative.'},{id:'dragon-communion-seal',role:'Catalyst',note:'Somber +10. The spread meets 10 FTH / 10 ARC.'},{id:'rotten-breath',role:'Optional opener',note:'Requires 15 FTH / 12 ARC. A long cast; only attempt it in a safe window.'},{id:'winged-sword-insignia',role:'Successive hits',note:'Fits two-handed twinblade attacks.'},{id:'lord-of-bloods-exultation',role:'Conditional damage',note:'Triggers on nearby blood loss; loses value when no target can bleed.'},{id:'green-turtle',role:'Recovery',note:'Useful throughout progression.'},{id:'dragoncrest-greatshield',role:'Defense',note:'An earlier Dragoncrest variant is the progression alternative.'}],
      armor:'Use Bandit or light Knight pieces and a medium roll. Equip only the weapon you are using if carrying both puts you at 70% load. The two weapons are alternatives, not a powerstance pair.',
      flasks:'Try 10 Crimson / 4 Cerulean at 14 charges. Opaline Hardtear is a defensive option; Thorny Cracked Tear supports repeated hits late. Do not plan a fight around unlimited breath casting.',
      progression:[{stage:'Early · RL 20–40',text:'Replace the short starting knife if its reach frustrates you. Get Uchigatana in Deathtouched Catacombs and meet 11 STR / 15 DEX. Bloody Slash from Fort Haight can grant Blood affinity before Occult is available. Build Vigor first; Arcane only scales buildup on weapons with Arcane scaling.'},{stage:'Middle · RL 60–100',text:'Defeat Eleonora at the Second Church of Marika in Altus Plateau for the poleblade. Meet 12 STR / 21 DEX / 19 ARC. The Dragon Communion Seal comes from Fringefolk Hero’s Grave; its trap corridor and knight are reasons to return later.'},{stage:'Late · RL 120–150',text:'Reach 58 ARC and 30 DEX after Vigor 60. Find the Black Whetblade in Night’s Sacred Ground, Nokron, unlocked after Radahn. Apply Occult to Uchigatana while keeping Unsheathe. Complete Leyndell Catacombs for Lord of Blood’s Exultation only when prepared for its dungeon.'}],
      alternatives:['For bleed immunity or high fire resistance, use Occult Uchigatana’s physical attacks and change the conditional blood-loss talisman.','Blood affinity emphasizes buildup; Occult emphasizes Arcane-based physical scaling and preserves innate bleed on Uchigatana. Compare the menu at your stats instead of assuming Blood always wins.','Rotten Breath is an optional status plan. Boss resistance, animation length and FP cost can make ordinary weapon attacks safer.'],encounters:['radahn','malenia','radagon-elden-beast']},
    sections:[section('Pressure without overcommitting','Two-hand Eleonora’s Poleblade to use its connected twinblade moveset. Build the successive-hit bonus with safe short attacks, then spend a large opening on Bloodblade Dance. Do not force the full skill into a fast enemy’s retaliation.','Blood loss buildup and damage are different. Arcane helps supported weapon scaling; it does not make every enemy vulnerable. Against a target with repeated hemorrhage resistance increases, keep dealing direct damage rather than waiting for one more proc.'),section('Keep a second plan','Occult Uchigatana is the important fallback here. Radagon and Elden Beast are immune to hemorrhage; a blood-loss talisman and a buildup-focused rotation will not create a proc. Physical hits still work.','The seal’s Arcane scaling does not make every healing or weapon-buff incantation scale fully with Arcane. This spread can cast Rotten Breath but cannot cast Golden Vow at 25 Faith. No DLC equipment is needed.')],related:['eleonoras-poleblade','uchigatana','bloody-slash','dragon-communion-seal','rotten-breath','affinities'],sources:[wiki("Eleonora's Poleblade"),wiki('Uchigatana'),wiki('Arcane'),wiki('Dragon Communion Seal'),wiki('Bandit')]},
  {...base('ensis-wanderer','Ensis Wanderer','build','Dexterity','A light greatsword, a deliberate stance, and room to adapt in the Realm of Shadow.','sword',true),tags:['Dexterity','DLC','Melee'],
    build:{className:'Samurai',level:150,stats:{VIG:60,MND:20,END:32,STR:12,DEX:80,INT:9,FTH:8,ARC:8},core:['DEX'],
      loadout:[{id:'milady',role:'Main hand',note:'Keen +25; 12 STR / 17 DEX. Requires Shadow of the Erdtree.'},{id:'wing-stance',role:'Skill',note:'DLC Ash of War for infusable light greatswords. Iron Whetblade enables Keen.'},{id:'winged-sword-insignia',role:'Successive attacks',note:'Works with the multi-hit light stance follow-up.'},{id:'shard-of-alexander',role:'Skill damage',note:'Base-game late reward; not mandatory.'},{id:'green-turtle',role:'Recovery',note:'Base-game option; no DLC turtle talisman required.'},{id:'dragoncrest-greatshield',role:'Defense',note:'Replace for an encounter’s dominant elemental damage if needed.'}],
      armor:'Begin the expansion in the Land of Reeds or Knight set. Use 32 Endurance to leave room for mixed armor, but always check the actual load after equipping. This build does not assume any stat-boosting helmet or Great Rune.',
      flasks:'Try 10 Crimson / 4 Cerulean at 14 charges. Dexterity-knot is an early option; Opaline Hardtear remains useful in the DLC. Do not treat a Physick as a substitute for collecting Scadutree Fragments.',
      progression:[{stage:'Base game · before DLC',text:'Play Keen Uchigatana with Unsheathe and upgrade it while building Vigor. Defeat Starscourge Radahn and Mohg, Lord of Blood to access the expansion through Miquella’s cocoon. Milady is not available in an ordinary Limgrave start.'},{stage:'Early expansion · Gravesite Plain',text:'Collect accessible Scadutree Fragments and activate their blessing at a Site of Grace. Find Milady in Castle Ensis and Wing Stance in a separate tower accessed near Castle-Lord’s Chamber. You can use Milady’s default Impaling Thrust before obtaining the stance.'},{stage:'Established DLC · RL 150',text:'Use Keen affinity, Vigor 60 and Dexterity 80. Continue upgrading your Scadutree Blessing through exploration. Practice the neutral moveset before adding stance attacks against Rellana or Messmer. A base-game +25 weapon does not remove the expansion’s blessing progression.'}],
      alternatives:['Keep Keen Uchigatana as the fully base-game substitute; it fits the exact listed stats.','For a safer learning run, use ordinary light and heavy attacks instead of holding Wing Stance in front of an active boss.','Rellana’s Cameo is a possible DLC stance accessory, but holding a stance for its bonus adds risk. It is not required by this version.'],encounters:['rellana','messmer','malenia']},
    sections:[section('Choose the branch that fits','Wing Stance’s light input produces multiple slashes; the heavy input is a leaping thrust. The light branch suits a long close-range recovery. The heavy branch reaches forward, so verify that the boss is finishing rather than beginning an attack.','Milady’s regular heavy attacks are worth learning. They give a pressure option without stance setup and can connect more than once. Do not label every airborne skill a jump attack: Claw Talisman does not automatically boost Wing Stance.'),section('The expansion rule','Shadow of the Erdtree is required for both Milady and Wing Stance. The other published equipment is from the base game. Scadutree Blessing works in the Realm of Shadow and does not raise base-game damage when you travel back.','This edition covers the original base game and Shadow of the Erdtree. Patch 1.17 also introduces Tarnished Pack content; the builds here require none of that pack’s new classes or equipment.')],related:['milady','wing-stance','shadow-entry','stance-and-survival','rellana','messmer'],sources:[wiki('Milady'),wiki('Skill: Wing Stance'),wiki('Scadutree Fragment'),patchSource,wiki('Samurai')]},
];

export const equipment:RecordNode[]=[
  {...base('greatsword','Greatsword','weapon','Colossal sword','A 23-weight colossal sword for Heavy affinity and deliberate stance pressure.','greatsword'),requirements:{STR:31,DEX:12},facts:[['Upgrade','Smithing Stones · +25'],['Weight','23.0'],['Default skill','Stamp (Upward Cut)'],['Affinity','Changeable · Heavy recommended for Strength']],
    sections:[section('Acquisition','Open the chest at the rear of the carriage on the road northwest of Caelem Ruins in Caelid. The giant dogs nearby can kill an early character; take the chest and retreat on Torrent. You do not need to defeat them.'),section('Use and affinity','21 Strength is enough when two-handing, with 12 Dexterity still required. One-handed use requires 31 Strength. Heavy affinity supports a Strength build; equip Lion’s Claw for a committed punish or keep a simpler skill while learning.','The crouching and rolling thrusts offer a quicker response than a charged heavy. Its weight competes with your armor budget: check medium load before entering a boss arena.')],related:['colossal-knight','lions-claw','affinities'],sources:[wiki('Greatsword')]},
  {...base('bloodhounds-fang',"Bloodhound’s Fang",'weapon','Curved greatsword','An early Somber weapon with a retreating skill, physical damage and innate bleed.','curved'),requirements:{STR:18,DEX:17},facts:[['Upgrade','Somber Smithing Stones · +10'],['Weight','11.5'],['Skill','Bloodhound’s Finesse · fixed'],['Affinity','Fixed · cannot infuse']],
    sections:[section('Acquisition','Defeat Bloodhound Knight Darriwil in Forlorn Hound Evergaol in southern Limgrave. Meet Blaidd in Mistwood and progress his dialogue if you want his help inside the evergaol. This is a boss reward, not a weapon lying in the overworld.'),section('A useful exception','Unlike most Somber weapons, Fang accepts weapon buffs. This does not mean its skill or affinity can be changed. The Bloodhound Ranger spread does not meet Bloodflame Blade’s spell requirements; a buff needs its own investment.','Arcane does not improve its innate bleed because it has no Arcane scaling. Use the skill’s follow-up only after checking the enemy’s next action. Jump attacks are a separate way to exploit a long recovery.')],related:['bloodhound-ranger','claw-talisman','stance-and-survival'],sources:[wiki("Bloodhound's Fang")]},
  {...base('uchigatana','Uchigatana','weapon','Katana','A starting katana that supports Keen, Magic, Blood or Occult plans.','katana'),requirements:{STR:11,DEX:15},facts:[['Upgrade','Smithing Stones · +25'],['Weight','5.5'],['Default skill','Unsheathe'],['Affinity','Changeable · innate blood loss']],
    sections:[section('Acquisition','Samurai starts with one. Other classes can find one on a corpse in Deathtouched Catacombs in northern Limgrave. There is one dungeon copy per world; two copies in a first playthrough require the Samurai start or a player trade.'),section('Choose for your stats','Keen favors a Dexterity investment. Occult lets Arcane support physical scaling and also scales the katana’s innate bleed. Blood affinity trades some direct-damage potential for buildup. The Black Whetblade needed for broader Occult choices is in Nokron, after Radahn.','Unsheathe’s heavy branch is a short, useful punish. An applied Unsheathe Ash of War lets you retain the skill while changing affinity. Elemental and status affinities generally prevent external grease or spell buffs; do not promise a buffed Occult katana.')],related:['unsheathe','bloody-slash','dragonblood-duelist','affinities'],sources:[wiki('Uchigatana'),wiki('Ash of War: Unsheathe')]},
  {...base('moonveil','Moonveil','weapon','Katana','A fixed Intelligence katana for a caster who wants a close-range fallback.','katana'),requirements:{STR:12,DEX:18,INT:23},facts:[['Upgrade','Somber Smithing Stones · +10'],['Weight','6.5'],['Skill','Transient Moonlight · fixed'],['Damage','Physical / magic · innate bleed']],
    sections:[section('Acquisition','Defeat the Magma Wyrm at the end of Gael Tunnel on the Limgrave–Caelid border. The tunnel is accessible early, but the boss is a significant obstacle for a fresh caster. Bring a physical damage option and learn the magma charges.'),section('Spend FP with purpose','Transient Moonlight combines a draw slash with a magic wave. A hit from just the projectile is not equivalent to connecting both blade and wave. Do not repeat old patch claims about automatic stance breaks.','Invest in Intelligence for this hybrid role after meeting the melee requirements and raising Vigor. Magic-resistant enemies are a reason to change tools; Rock Sling offers physical ranged damage. Its skill and affinity are fixed, and external buffs are unavailable.')],related:['carian-spellblade','rock-sling','carian-slicer'],sources:[wiki('Moonveil'),wiki('Katana')]},
  {...base('blasphemous-blade','Blasphemous Blade','weapon','Greatsword','A Faith-oriented fire skill with healing on connected flame hits.','flame'),requirements:{STR:22,DEX:15,FTH:21},facts:[['Upgrade','Somber Smithing Stones · +10'],['Weight','13.5'],['Skill','Taker’s Flames · fixed'],['Damage','Physical / fire']],
    sections:[section('Acquisition','Defeat Rykard, Lord of Blasphemy, then trade his remembrance with Enia at Roundtable Hold. Complete any Volcano Manor contracts you want first: defeating Rykard changes manor progression. Serpent-Hunter is the intended tool for that encounter; this blade is the reward afterward.'),section('A strong tool with limits','Faith supports the fire wave of Taker’s Flames. The skill heals when its flame hits a target, but the animation is a real commitment. Choose an opening with a clear line rather than hoping hyperarmor will make the exchange safe.','Its flame no longer has the old knockdown effect after patch 1.12. Fire-resistant bosses, especially Messmer, call for a lightning or physical alternative. The blade cannot receive a new Ash of War, affinity or external weapon buff.')],related:['blasphemous-pilgrim','lightning-spear','golden-vow'],sources:[wiki('Greatswords'),wiki('Remembrance of the Blasphemous'),wiki("Unique Skill: Taker's Flames")]},
  {...base('eleonoras-poleblade',"Eleonora’s Poleblade",'weapon','Twinblade','An Arcane twinblade with fixed fire damage and a long multi-hit skill.','twinblade'),requirements:{STR:12,DEX:21,ARC:19},facts:[['Upgrade','Somber Smithing Stones · +10'],['Weight','6.0'],['Skill','Bloodblade Dance · fixed'],['Damage','Physical / fire · blood loss']],
    sections:[section('Acquisition','Defeat the invading Eleonora at the Second Church of Marika in Altus Plateau. Yura’s quest provides context for this encounter. It is a midgame pickup, so use another weapon while building the required Dexterity and Arcane.'),section('Commit only in a real opening','Two-handed attacks suit the twinblade’s multiple hits. Bloodblade Dance is a larger commitment and should follow a boss’s confirmed recovery. Its bleed benefits from Arcane scaling, unlike Bloodhound’s Fang.','Both fire resistance and blood-loss immunity reduce the appeal of its normal plan. Keep an Occult physical weapon available. The poleblade cannot change skill or affinity, and cannot be buffed by grease or spells.')],related:['dragonblood-duelist','winged-sword-insignia','lord-of-bloods-exultation','uchigatana'],sources:[wiki("Eleonora's Poleblade"),wiki('Twinblades')]},
  {...base('milady','Milady','weapon','Light greatsword','A flexible light greatsword with connected heavy attacks and access to Wing Stance.','sword',true),requirements:{STR:12,DEX:17},facts:[['Expansion','Shadow of the Erdtree'],['Upgrade','Smithing Stones · +25'],['Weight','6.5'],['Default skill','Impaling Thrust'],['Affinity','Changeable · Keen in Ensis Wanderer']],
    sections:[section('Acquisition','Find the chest at the top of a watchtower in Castle Ensis. Explore the castle’s tower paths and ladders; Wing Stance is in a separate chest and is not Milady’s default skill. Shadow of the Erdtree access is required.'),section('Use the ordinary moveset too','The light greatsword’s connected heavy attacks let you make progress without constant skill use. Keen suits the 80 Dexterity Ensis Wanderer. Other affinities can fit different spreads, but that is a separate build decision.','Wing Stance offers a multi-slash light branch and a leaping thrust heavy branch. Use it after learning the weapon’s reach. Raising Scadutree Blessing has more practical value in the expansion than assuming an upgraded weapon alone will carry the run.')],related:['ensis-wanderer','wing-stance','shadow-entry'],sources:[wiki('Milady'),wiki('Light Greatswords')]},
  {...base('brass-shield','Brass Shield','weapon','Shield','Full physical blocking with an early farm, balanced against a 7-weight load cost.','shield'),requirements:{STR:16},facts:[['Upgrade','Smithing Stones · +25'],['Weight','7.0'],['Default skill','No Skill'],['Physical negation','100% while successfully blocking']],
    sections:[section('Acquisition','Farm soldiers carrying the brass-colored triangular shield around Gatefront or other soldier camps. It is a random drop, so avoid treating it as a guaranteed chest reward. A starting 100% physical shield is a fine alternative while you wait.'),section('Guard without exhausting yourself','No Skill passes the skill input to the right-hand weapon. Shield upgrades improve guard performance; raising attack stats alone does not make blocking cheap. Lower the shield between enemy attacks to regain stamina.','100% physical negation does not block every damage type, status buildup, grab or entire combo safely. Guard counter after the final manageable hit, not after the first. A guard break leaves you vulnerable.')],related:['bloodhound-ranger','stance-and-survival'],sources:[wiki('Medium Shields')]},
  {...base('carian-regal-scepter','Carian Regal Scepter','weapon','Staff','A late Intelligence catalyst without an increased casting FP cost.','staff'),requirements:{STR:8,DEX:10,INT:60},facts:[['Upgrade','Somber Smithing Stones · +10'],['Weight','3.0'],['Requirement','60 Intelligence'],['Passive','Boosts full-moon sorceries']],
    sections:[section('Acquisition','Trade Rennala’s Remembrance of the Full Moon Queen with Enia. Obtaining the staff does not mean you can use it immediately: its 60 Intelligence requirement is much higher than most early catalysts.'),section('Upgrade before comparing','Use a leveled starting staff or a suitable intermediate catalyst until you meet the requirement. Compare sorcery scaling at the same upgrade tier and your current Intelligence; the scepter is not the best answer at every low level.','Its full-moon bonus does not apply to every sorcery. Carian Slicer and Rock Sling benefit from the catalyst’s general scaling, with magic and physical damage respectively. The fixed Spinning Weapon skill is not a replaceable Ash of War slot.')],related:['carian-spellblade','carian-slicer','rock-sling','upgrades-and-rebirth'],sources:[wiki('Carian Regal Scepter')]},
  {...base('finger-seal','Finger Seal','weapon','Sacred seal','An accessible Faith catalyst that you can keep upgraded throughout the base game.','seal'),requirements:{STR:4,FTH:10},facts:[['Upgrade','Smithing Stones · +25'],['Weight','1.5'],['Use','Cast incantations'],['Skill','No Skill']],
    sections:[section('Acquisition','Confessor and Prophet begin with a Finger Seal. Other classes can buy it from the Twin Maiden Husks at Roundtable Hold. It uses normal Smithing Stones, so plan resources if your sword also needs the same stones.'),section('A practical baseline','Meet both the seal’s requirements and the spell’s separate Faith or Arcane requirements. Upgrade the seal to improve scaling for supported damage and healing spells. Golden Vow’s fixed buff is not made stronger by upgrading a seal.','High-Faith characters can compare other seals later. This archive uses Finger Seal as an accessible baseline and does not claim it leads every scaling chart. Sacred seals cannot take an Ash of War.')],related:['blasphemous-pilgrim','lightning-spear','golden-vow'],sources:[wiki('Finger Seal'),wiki('Sacred Seals'),wiki('Incantation Scaling')]},
  {...base('dragon-communion-seal','Dragon Communion Seal','weapon','Sacred seal','A weightless Arcane/Faith seal for Dragon Communion damage spells.','seal'),requirements:{FTH:10,ARC:10},facts:[['Upgrade','Somber Smithing Stones · +10'],['Weight','0.0'],['Scaling','Faith / Arcane'],['Passive','Boosts Dragon Communion incantations']],
    sections:[section('Acquisition','Defeat the spectral Banished Knight on the upper branch of Fringefolk Hero’s Grave. The entrance near Stranded Graveyard uses Stonesword Keys. The chariot and knight make this a dangerous early detour; return with more HP if needed.'),section('Understand the split','It works well when your build already invests in Arcane and enough Faith for its spells. Its Dragon Communion bonus supports Rotten Breath’s direct damage, but does not promise a stronger scarlet-rot status tick.','Healing and weapon-buff incantations do not use every part of hybrid seal scaling in the same way as attack spells. This is an offensive catalyst for the Dragonblood Duelist, not a universal replacement for a pure Faith seal.')],related:['dragonblood-duelist','rotten-breath'],sources:[wiki('Dragon Communion Seal'),wiki('Incantation Scaling')]},

  {...base('lions-claw',"Lion’s Claw",'ash','Heavy','A committed forward somersault for infusable swords, axes and hammers.','greatsword'),facts:[['Default affinity','Heavy'],['FP','20'],['Compatibility','Eligible swords, axes, hammers; not daggers or thrusting swords']],
    sections:[section('Find and equip','Defeat the lion inside Fort Gael in Caelid. Apply the Ash of War at a Site of Grace with the Whetstone Knife, or ask a smith. Greatsword is compatible; Bloodhound’s Fang and other fixed-skill Somber weapons are not.'),section('Use after the chain','Hyperarmor helps the attack complete through some hits, but you still take damage. Use it after a long recovery and keep enough stamina to escape. It is not an ordinary jump attack and does not receive Claw Talisman’s jump bonus.','Heavy is a useful match for Colossal Knight. Other affinities depend on whetblades and compatibility; an Ash’s default affinity is not the only possible selection.')],related:['colossal-knight','greatsword','affinities','shard-of-alexander'],sources:[wiki("Skill: Lion's Claw"),wiki('Elder Lion')]},
  {...base('unsheathe','Unsheathe','ash','Keen','A quick katana stance with separate horizontal and overhead punish options.','katana'),facts:[['Default affinity','Keen'],['FP','10 light / 15 heavy follow-up'],['Compatibility','Infusable katanas']],
    sections:[section('Keep the skill, change the affinity','Uchigatana starts with Unsheathe. The transferable Ash drops from a scarab in southeastern Agheel Lake, Limgrave. Applying it is useful when you want to change the katana’s affinity while preserving its familiar stance.'),section('Pick one opening','Hold the skill input, then choose light for the horizontal slash or heavy for the overhead strike. Holding the stance slows your movement and is not a defensive action. The heavy branch supports stance pressure, but repeated use needs safe windows.','With the Black Whetblade, a physical Ash such as Unsheathe can support Occult on an eligible katana. Moonveil’s Transient Moonlight is a distinct fixed skill and cannot be replaced with this Ash.')],related:['uchigatana','dragonblood-duelist','affinities'],sources:[wiki('Ash of War: Unsheathe'),wiki('Skill: Unsheathe')]},
  {...base('bloody-slash','Bloody Slash','ash','Blood','An early Blood-affinity option with a self-HP cost on the skill.','katana'),facts:[['Default affinity','Blood'],['Acquisition','Fort Haight knight'],['Tradeoff','Skill consumes HP as well as FP']],
    sections:[section('Acquisition','Defeat the blood-using knight at the top of Fort Haight in eastern Limgrave. Apply to a compatible sword. Uchigatana is an early practical candidate; fixed Somber weapons cannot take it.'),section('Affinity and skill do different jobs','Selecting Blood affinity adds or changes bleed buildup on an eligible weapon. The skill’s red slash is not a reason to assume every hit automatically procs hemorrhage. Its HP cost becomes risky when you are already close to death.','Use normal attacks to learn the enemy first. Dragonblood Duelist can start with a Blood weapon, then move to an Occult innate-bleed katana after Nokron. Against a bleed-immune boss, prioritize direct damage and another talisman over proc-dependent bonuses.')],related:['uchigatana','dragonblood-duelist','affinities'],sources:[wiki('Godrick Knight'),wiki('Ash of War: Bloody Slash')]},
  {...base('wing-stance','Wing Stance','ash','Quality','A light greatsword stance with a multi-slash branch and leaping thrust.','sword',true),facts:[['Expansion','Shadow of the Erdtree'],['Default affinity','Quality'],['FP','8 light / 10 heavy follow-up'],['Compatibility','Infusable light greatswords']],
    sections:[section('Acquisition','Find the tower chest reached from the cliffside below Castle-Lord’s Chamber in Castle Ensis. Follow the outside ledges carefully. This is a separate pickup from Milady, whose default skill is Impaling Thrust.'),section('Match the affinity to the build','Use the Iron Whetblade to choose Keen for Ensis Wanderer. Default Quality does not make a high-Dexterity, low-Strength character a Quality build. The light branch benefits from connecting multiple hits; the heavy branch covers forward distance.','The leaping skill is not an ordinary jump attack for Claw Talisman. A stance is an offensive setup, not invulnerability. Against Rellana’s long strings, ordinary attacks after the final hit are often the safer starting point.')],related:['milady','ensis-wanderer','winged-sword-insignia','rellana'],sources:[wiki('Ash of War: Wing Stance'),wiki('Skill: Wing Stance')]},

  {...base('green-turtle','Green Turtle Talisman','talisman','Recovery','An early stamina recovery slot that helps almost every melee plan.','turtle'),facts:[['Acquisition','Summonwater Village cellar'],['Access','One Stonesword Key'],['Role','Faster stamina recovery']],
    sections:[section('Collect it early','Open the sealed cellar in Summonwater Village in northern Limgrave using one Stonesword Key. Take the talisman from the chest. The nearby Tibia Mariner is a separate encounter.'),section('Give recovery time to work','Faster recovery is useful between actions; it does not increase the size of your stamina bar or remove attack costs. Lower a shield and pause your chain to take advantage of it.','Use this slot when a failed attempt ends with an empty green bar. It cannot stack with the DLC Two-Headed Turtle Talisman, since those are variants of the same talisman family.')],related:['stance-and-survival','colossal-knight','bloodhound-ranger'],sources:[wiki('Green Turtle Talisman')]},
  {...base('axe-talisman','Axe Talisman','talisman','Charged attacks','Supports fully charged melee heavies; it is not a generic skill bonus.','talisman'),facts:[['Acquisition','Mistwood Ruins cellar'],['Role','Charged heavy melee attacks']],
    sections:[section('Acquisition','Take it from the cellar chest at Mistwood Ruins in eastern Limgrave. A Runebear sleeps near the entrance. You can retrieve the chest without winning a prolonged fight, but noise and poor positioning can wake it.'),section('Use the right input','Choose this when fully charged heavies are part of your plan. A quick tap heavy, a jump heavy or Lion’s Claw does not become a charged melee attack just because it looks forceful.','For Colossal Knight, wait for a long recovery before charging. If you mostly use the skill, replace this with an appropriate defense or skill slot; theoretical damage means little if the charge never finishes.')],related:['colossal-knight','greatsword','stance-and-survival'],sources:[wiki('Axe Talisman')]},
  {...base('claw-talisman','Claw Talisman','talisman','Jump attacks','A focused bonus for ordinary jumping weapon attacks.','talisman'),facts:[['Acquisition','Stormveil Castle rooftop'],['Role','Jumping weapon attacks']],
    sections:[section('Acquisition','Explore the rooftops above the Rampart Tower area in Stormveil Castle and climb the tower ladder to the corpse holding the talisman. Check drop routes carefully; reaching a rooftop is not always a safe jump back.'),section('Avoid the animation trap','Bloodhound’s Fang has useful ordinary jump attacks, making this a natural slot for its Ranger build. A skill that leaps is still a skill: Lion’s Claw and Wing Stance do not automatically receive this bonus.','Jumping can avoid some low attacks, but it does not give complete invulnerability. Use a jump punish after the enemy commits, then recover rather than chaining another attack blindly.')],related:['bloodhound-ranger','bloodhounds-fang','stance-and-survival'],sources:[wiki('Claw Talisman')]},
  {...base('shard-of-alexander','Shard of Alexander','talisman','Skill damage','A late quest reward for builds that regularly connect weapon skills.','talisman'),facts:[['Acquisition','Alexander’s quest · Farum Azula'],['Role','Weapon skill damage'],['Missable','Do not kill Alexander early']],
    sections:[section('Follow the quest','Keep Alexander alive, speak to him through his journey, and meet him for the final duel in Crumbling Farum Azula. His earlier death gives Warrior Jar Shard instead and ends the quest. Neither item is an honest early-game requirement.'),section('What it boosts','Use it for Lion’s Claw, Bloodhound’s Finesse, Transient Moonlight, Taker’s Flames or Wing Stance when those skills actually land. It is not a general boost to light attacks, Carian Slicer or Lightning Spear.','Shard of Alexander and Warrior Jar Shard are mutually exclusive. The published builds remain functional before this reward; a defensive talisman is a reasonable interim choice.')],related:['colossal-knight','blasphemous-pilgrim','ensis-wanderer'],sources:[wiki('Shard of Alexander'),wiki('Alexander, Warrior Jar')]},
  {...base('dragoncrest-greatshield','Dragoncrest Greatshield Talisman','talisman','Physical defense','Late-game physical protection, with earlier Dragoncrest variants as substitutes.','shield'),facts:[['Acquisition','Elphael · Drainage Channel route'],['Role','Physical damage negation'],['Limitation','Does not reduce elemental damage']],
    sections:[section('Acquisition','From Drainage Channel in Elphael, follow roots and buttresses to the nearby church roof. Drop through the opening onto the rafters and reach the chest on the upper platform. Pests below make a careless drop dangerous.'),section('Choose defense for the hit','It reduces physical damage received in PvE. Fire, magic, lightning and holy hits call for their own protection. A mixed attack can contain both physical and elemental portions, so physical defense alone is incomplete.','Use an earlier Dragoncrest Shield variant before the Haligtree. Variants cannot be equipped together. For an unfamiliar boss, survival can provide more learning time than a fourth damage talisman.')],related:['malenia','radagon-elden-beast','stance-and-survival'],sources:[wiki('Dragoncrest Greatshield Talisman')]},
  {...base('winged-sword-insignia','Winged Sword Insignia','talisman','Successive hits','An accessible reward for weapons that connect several hits in a short window.','talisman'),facts:[['Acquisition','Stillwater Cave boss · Liurnia'],['Role','Successive attacks'],['Limitation','Bonus decays without pressure']],
    sections:[section('Acquisition','Defeat the Cleanrot Knight at the end of Stillwater Cave in southern Liurnia. Prepare for the cave’s poison and preserve enough healing for the boss. It is an early-to-midgame dungeon reward.'),section('Pressure is conditional','Two-handed twinblade attacks and Wing Stance’s connected light branch can build the bonus. A single isolated colossal hit is a less natural fit. The effect needs successive connections and falls away when pressure stops.','Do not trade HP just to preserve the bonus. Winged Sword Insignia and Rotten Winged Sword Insignia are variants and cannot be equipped together. This edition uses the earlier item rather than requiring Millicent’s late quest reward.')],related:['dragonblood-duelist','ensis-wanderer','wing-stance'],sources:[wiki('Winged Sword Insignia')]},
  {...base('lord-of-bloods-exultation',"Lord of Blood’s Exultation",'talisman','Blood loss','A conditional damage slot that needs blood loss nearby to do anything.','talisman'),facts:[['Acquisition','Esgar · Leyndell Catacombs'],['Role','Damage after nearby blood loss'],['Limitation','No proc against hemorrhage immunity']],
    sections:[section('Acquisition','Defeat Esgar, Priest of Blood in Leyndell Catacombs, beneath the capital. This is a confusing, dangerous dungeon and not an obligatory detour for an early bleed character.'),section('Have a replacement ready','The bonus activates when blood loss occurs nearby; merely holding a bleed weapon does not turn it on. Dragonblood Duelist can make use of it in bleed-susceptible encounters.','Radagon and Elden Beast are immune to hemorrhage. Replace the conditional slot for that fight and use physical damage. Self-bleed setups exist, but this build does not require them and does not assume a proc before every fog gate.')],related:['dragonblood-duelist','malenia','radagon-elden-beast'],sources:[wiki("Lord of Blood's Exultation")]},

  {...base('carian-slicer','Carian Slicer','spell','Sorcery','A fast, short-range magic blade for the moment an enemy closes the gap.','staff'),requirements:{INT:14},facts:[['Catalyst','Glintstone staff'],['Memory slots','1'],['Damage','Magic']],
    sections:[section('Acquisition','Collect the Royal House Scroll in southern Limgrave and give it to an eligible sorcery teacher such as Sellen. Buy Carian Slicer after turning in the scroll. The spell needs 14 Intelligence and a staff.'),section('Close-range casting','It is a compact melee spell, useful when a ranged casting plan runs out of space. Move into a confirmed opening and cast a short chain, leaving stamina to dodge. It is not a block, parry or physical sword attack.','Against high magic resistance, switch to physical damage rather than trying to force Slicer. Shard of Alexander does not boost sorceries. A staff’s sorcery scaling and magic-oriented support affect the appropriate damage.')],related:['carian-spellblade','carian-regal-scepter','rennala'],sources:[wiki('Carian Slicer')]},
  {...base('rock-sling','Rock Sling','spell','Sorcery','A physical-damage sorcery with slow travel and meaningful stance pressure.','staff'),requirements:{INT:18},facts:[['Catalyst','Glintstone staff'],['Memory slots','1'],['Damage','Physical']],
    sections:[section('Acquisition','Find the underground chest in Street of Sages Ruins in the Swamp of Aeonia, Caelid. Meteorite Staff is nearby and boosts gravity sorceries, but cannot be upgraded. The trip is possible early and dangerous.'),section('Clear the line of sight','Rocks can clip walls or miss a moving target. Cast with enough room and time for them to leave the staff and travel. This is a physical damage option for an Intelligence character facing magic resistance.','Physical damage does not mean every cast is safe. Rennala’s spell pressure and summons still require movement. Magic damage buffs do not boost the physical component of Rock Sling; avoid judging it by the color of the casting effect.')],related:['carian-spellblade','rennala','radahn'],sources:[wiki('Rock Sling')]},
  {...base('lightning-spear','Lightning Spear','spell','Incantation','A compact lightning projectile for a Faith build’s ranged damage slot.','seal'),requirements:{FTH:17},facts:[['Catalyst','Sacred seal'],['Memory slots','1'],['Damage','Lightning']],
    sections:[section('Acquisition','Defeat the knight carrying the Dragon Cult Prayerbook south of Artist’s Shack in eastern Liurnia. Give the book to an incantation teacher such as Miriel, then buy Lightning Spear. It requires 17 Faith.'),section('An alternate damage type','Use it when the target resists fire or when a sword skill leaves you too exposed. Charge only when the opening lasts long enough; a fast uncharged cast can be the better punish.','Golden Vow can support it, but Flame, Grant Me Strength boosts physical and fire damage instead. Upgrade the seal and check spell requirements independently. Lightning is not an automatic weakness for every large enemy.')],related:['blasphemous-pilgrim','finger-seal','messmer'],sources:[wiki('Lightning Spear')]},
  {...base('golden-vow','Golden Vow','spell','Incantation','An aura buff for damage and defense, distinct from the Ash of War of the same name.','seal'),requirements:{FTH:25},facts:[['Catalyst','Sacred seal'],['Memory slots','1'],['Category','Aura buff']],
    sections:[section('Acquisition','Collect the incantation at Corpse-Stench Shack in Mt. Gelmir. It needs 25 Faith. The Golden Vow Ash of War is a different version with different values; owning that Ash does not let you cast this spell.'),section('A simple pre-fight routine','Cast before the fog when safe, then use your shorter body buff if the build includes one. Golden Vow can coexist with Flame, Grant Me Strength because they occupy different categories. Recasting the same aura does not stack another copy.','Upgrading a seal does not raise this fixed buff’s strength. Do not interrupt a boss fight to refresh it without an opening. Dragonblood Duelist at 15 Faith cannot cast this version.')],related:['blasphemous-pilgrim','flame-grant-me-strength','finger-seal'],sources:[wiki('Golden Vow'),wiki('Buffs')]},
  {...base('flame-grant-me-strength','Flame, Grant Me Strength','spell','Incantation','A short body buff for physical and fire damage, with clear stacking limits.','seal'),requirements:{FTH:15},facts:[['Catalyst','Sacred seal'],['Memory slots','1'],['Category','Body buff'],['Damage support','Physical / fire']],
    sections:[section('Acquisition','Pick it up behind Fort Gael in Caelid, near the flame chariots. It requires 15 Faith. You can collect it without clearing the fort, but the enemies punish a slow approach.'),section('Use it for the correct damage','It supports physical attacks and Taker’s Flames fire damage; it does not increase magic or lightning damage. Cast after a longer aura buff so less of the short duration is spent preparing.','It can coexist with Golden Vow, but other body buffs such as defensive fortifications or Exalted Flesh can replace it. Against an unfamiliar fight, a defensive body buff may be the better choice. Refreshing it is optional, not a mandatory rotation.')],related:['blasphemous-pilgrim','golden-vow','blasphemous-blade'],sources:[wiki('Flame, Grant Me Strength'),wiki('Buffs')]},
  {...base('rotten-breath','Rotten Breath','spell','Dragon Communion','A long physical breath with scarlet-rot buildup, best treated as a situational opener.','seal'),requirements:{FTH:15,ARC:12},facts:[['Catalyst','Sacred seal'],['Memory slots','1'],['Damage','Physical + scarlet-rot buildup']],
    sections:[section('Acquisition','Spend one Dragon Heart at the Cathedral of Dragon Communion in southern Caelid. You need 15 Faith, 12 Arcane and a seal. A Dragon Heart comes from an eligible dragon encounter, not an ordinary rune purchase.'),section('A cast needs room','The windup and channel leave you exposed. Use a long confirmed opening or an ally’s distraction; abandon the idea if the boss can reach you before the breath connects. A status plan is not a reason to stand still inside a combo.','The Dragon Communion Seal boosts the spell’s direct damage, not a guaranteed stronger rot damage-over-time effect. Rot-resistant or immune enemies need a different plan. Patch 1.17’s listed Rotten Breath adjustment is PvP-specific; do not misapply it as a PvE damage change.')],related:['dragonblood-duelist','dragon-communion-seal','radahn'],sources:[wiki('Rotten Breath'),wiki('Dragon Communion Incantations'),patchSource]},
];

export const bosses:RecordNode[]=[
  {...base('margit','Margit, the Fell Omen','boss','Stormveil approach','Delayed attacks, short punish windows, and your first lesson in resisting the panic roll.','boss'),facts:[['Location','Castleward Tunnel · Stormhill'],['Progression','Early base game'],['Preparation','Medium roll; upgraded main weapon; enough Vigor']],
    sections:[section('Before the fog','Explore Limgrave and the Weeping Peninsula if one hit nearly kills you. Upgrade one weapon, add flask charges with Golden Seeds, and strengthen healing with Sacred Tears. Margit is a route gate to Stormveil, not a demand to defeat him immediately.','Margit’s Shackle can restrain him twice during the first phase. Patches sells it after his encounter in Murkwater Cave. Sorcerer Rogier and available Spirit Ashes are legitimate support options; a summon changes targeting but does not erase the need to dodge.'),section('Read the hand, not the windup','When he raises the staff and holds it, wait for the release instead of rolling immediately. Dodge through the committed swing and answer with one quick attack. A tail swipe can punish staying behind him, so watch for the next turn.','The golden hammer adds range and follow-ups. A leaping hammer attack can offer a punish after landing, but stop after one attack until you know the chain is finished. Healing from neutral distance can draw a dagger throw.'),section('If the next attempt fails','If you roll early, spend a few attempts defending without chasing damage. If you run out of stamina, shorten your punish. Unsheathe or a jump heavy can pressure stance, but a slow skill is only appropriate after a genuine recovery.','Bleed helps when it procs; it is not required. Your late RL150 build is a destination, not the stat spread you should expect at Margit.')],related:['first-route','stance-and-survival','bloodhound-ranger','uchigatana'],sources:[wiki('Margit the Fell Omen')]},
  {...base('rennala','Rennala, Queen of the Full Moon','boss','Raya Lucaria','Break the library shield, then switch to physical damage and move through the spell pressure.','moon'),facts:[['Location','Raya Lucaria Academy · Liurnia'],['Unlock','Rebirth with a Larval Tear'],['Damage choice','Physical is a useful answer to magic resistance']],
    sections:[section('Prepare the correct damage','An Intelligence character should bring a physical option such as Rock Sling rather than relying entirely on magic projectiles. A normal melee weapon works too. Keep enough Crimson charges for the second phase and avoid spending all your FP in the library.'),section('Library phase','Identify the singing scholars with golden light and interrupt them. After three interruptions, Rennala’s barrier breaks and she falls. Move in for a short damage window, then leave before the barrier reforms. Watch falling objects and spell pressure while moving between scholars.'),section('Moonlit phase','Move sideways through the opening beam instead of committing to a long cast. Close distance between spells and use a quick punish. Her summoned allies are temporary: reposition around them instead of insisting on clearing every summon.','Rock Sling needs a clear lane. If it misses against movement, get closer during a recovery or switch to short physical melee. After victory, Rennala remains available for rebirth; you do not lose that service by defeating her.')],related:['carian-spellblade','rock-sling','upgrades-and-rebirth'],sources:[wiki('Rennala'),wiki('Rock Sling')]},
  {...base('radahn','Starscourge Radahn','boss','Caelid festival','Manage the opening arrows, use the festival allies, and track the meteor transition.','boss'),facts:[['Location','Wailing Dunes · Caelid'],['Access','Radahn Festival at Redmane Castle'],['Unlock','Nokron route; one of the DLC entry requirements']],
    sections:[section('Reach the festival','Activate the Radahn Festival through appropriate progression, commonly reaching Altus Plateau or advancing Ranni’s quest. Talk to Jerren at Redmane Castle and take the lift to the sending gate. This is Starscourge Radahn from the base game, a different encounter from the DLC final boss.'),section('Opening and melee','At long range, watch the gravity arrow release and dodge deliberately. The scattered NPC signs let festival allies join; use them if you want help dividing attention. Torrent is available, but being mounted does not make the opening projectiles harmless.','Once he commits to an ally, approach from an angle and punish briefly. His swords cover a wide arc. Do not spend the entire stamina bar attacking under him, since the next sweep can force several defensive actions.'),section('Transition and recovery','When he rises out of the arena, stop attacking, find open space and watch the sky for his meteor return. Moving on Torrent can help cover distance; do not stand still refreshing buffs. Return to short attacks once the landing resolves.','Rotten Breath is a possible status opener only when you have a safe cast. A direct physical weapon remains a reliable plan. Defeating him opens the crater route to Nokron, including the Black Whetblade used by the Arcane fallback.')],related:['bloodhound-ranger','dragonblood-duelist','rotten-breath','shadow-entry','affinities'],sources:[wiki('Starscourge Radahn'),wiki('Wailing Dunes'),wiki('Black Whetblade')]},
  {...base('mohg','Mohg, Lord of Blood','boss','Mohgwyn Palace','Prepare for the blood ritual, then fight on clean ground instead of standing in bloodflame.','boss'),facts:[['Location','Mohgwyn Dynasty Mausoleum'],['Preparation','Purifying Crystal Tear in Physick'],['Unlock','Miquella’s cocoon · DLC access']],
    sections:[section('Preparation changes the fight','Use the Purifying Crystal Tear dropped by Eleonora at the Second Church of Marika in your Flask of Wondrous Physick. Drink before the phase transition ritual. It greatly reduces ritual damage but does not stop Mohg’s healing.','Mohg’s Shackle, found in the Subterranean Shunning-Grounds, can restrain him during the first phase. The tear and shackle have different jobs. Bring fire protection and enough healing; the tear does not protect you from every bloodflame attack.'),section('First phase','Wait through his delayed trident attacks and punish the final swing. Bloodflame placement makes backing up in a straight line a poor habit. Move toward clear ground and keep a view of his weapon.','His counting marks lead to the ritual. Prepare your Physick before the transition; without the tear, healing can compensate, but costs charges you may need later. Do not assume ordinary rolling avoids the ritual.'),section('Second phase','His airborne approaches and bloodflame trails make arena space a resource. Dodge the approach, leave the burning ground, then attack. Standing still to channel a breath or cast a slow sword skill is especially risky here.','Mohg, Lord of Blood is the required Mohg for Shadow of the Erdtree entry. Defeating Mohg, the Omen in the capital sewers does not satisfy that requirement. You also need Starscourge Radahn.')],related:['eleonoras-poleblade','shadow-entry','radahn','stance-and-survival'],sources:[wiki('Mohg, Lord of Blood'),wiki('Purifying Crystal Tear'),wiki("Mohg's Shackle")]},
  {...base('malenia','Malenia, Blade of Miquella','boss','Elphael','A test of disciplined openings, heal-on-hit pressure, and learning Waterfowl at your current distance.','boss'),facts:[['Location','Haligtree Roots · Elphael'],['Progression','Optional late base game'],['Preparation','Physical defense; medium roll; rot response']],
    sections:[section('Do not give damage back','Malenia heals when her attacks connect, including successful hits into a blocking shield. Blocking can save a life, but passive shield play can lengthen the fight. Use short openings and return to a position where you can react.','Bring a rot cure or an eligible cleansing spell for the second phase. Bleed and fire are useful options, but neither guarantees a stagger on every hit. Taker’s Flames should not be treated as its older knockdown version.'),section('Waterfowl is a distance problem','Her rise into the air is the cue to stop attacking. With distance already available, sprint away from the first flurry, then dodge the later approaches as they close in. Do not begin a long skill as she rises.','At point-blank range, the sprint-away plan may not create enough separation. Close-range evasions demand a different practiced response; this guide does not promise a universal one-button solution. Keep shorter attack commitments so you can recognize the cue earlier.'),section('Second phase','Scarlet Aeonia begins with a dive and bloom. Avoid the dive, create space from the bloom, and wait until the damaging area permits a safe punish. Ranged attacks can use the recovery from outside the hazard.','Her added aerial and phantom sequences still demand patience. If the run fails because every punish becomes a trade, reduce to one attack and learn the next move before chasing more damage. Spirit Ash support is optional; it changes aggro and can also provide targets for her healing.')],related:['bloodhound-ranger','blasphemous-pilgrim','dragoncrest-greatshield','stance-and-survival'],sources:[wiki('Malenia'),wiki('Dragoncrest Greatshield Talisman'),wiki("Unique Skill: Taker's Flames")]},
  {...base('radagon-elden-beast','Radagon & Elden Beast','boss','Elden Throne','One flask budget for two fights: physical or fire for Radagon, and a patient chase for the Beast.','moon'),facts:[['Location','Elden Throne · final base-game encounter'],['Status','Both immune to hemorrhage'],['Preparation','Holy protection; direct-damage fallback'],['Mobility','Torrent is available during Elden Beast']],
    sections:[section('Build for both halves','Avoid a Holy damage plan and do not depend on hemorrhage. Use an upgraded physical weapon; fire is a useful Radagon option. Replace Lord of Blood’s Exultation if your strategy cannot trigger it. Holy protection helps against the encounter’s major elemental attacks.','Torrent became usable against Elden Beast in patch 1.12. The Radagon half remains on foot. Keep enough healing and FP for the second half rather than spending the entire budget forcing the first.'),section('Radagon: wait for the finish','His hammer strings and delayed holy slams punish early rolls. Dodge the release and take one short punish. When he begins a repeated slam sequence, track every impact; the first dodge is not the end of the attack.','Teleport bursts and projectile responses make neutral casting risky. Blasphemous Pilgrim should choose a confirmed recovery for Taker’s Flames instead of casting whenever HP is missing.'),section('Elden Beast: chase with a plan','Use Torrent to cover large gaps when appropriate, then dismount for attacks that need precise on-foot dodging. Watch the approaching sword waves rather than staring only at the boss’s distant body.','For the ring attack, move toward a gap and jump the closing ring as needed. Leave stamina for movement when projectiles overlap. It is immune to status effects: Occult Uchigatana’s direct physical damage is still useful, but its bleed buildup will never proc here.')],related:['colossal-knight','dragonblood-duelist','blasphemous-pilgrim','affinities'],sources:[wiki('Radagon of the Golden Order'),wiki('Elden Beast'),{label:'Bandai Namco: patch 1.12 · Torrent in final encounter',url:'https://en.bandainamcoent.eu/elden-ring/news/elden-ring-patch-notes-version-112'}]},
  {...base('rellana','Rellana, Twin Moon Knight','boss','Castle Ensis','Long twin-blade strings and three moon shockwaves reward a restrained punish plan.','boss',true),facts:[['Expansion','Shadow of the Erdtree'],['Location','Castle Ensis'],['Preparation','Scadutree Blessing; magic and fire defense']],
    sections:[section('Explore before forcing the gate','Use collected Scadutree Fragments at a Site of Grace before repeated attempts. If every mistake almost kills you, explore Gravesite Plain for more fragments rather than assuming Rune Level alone solves it. Her route leads to Scadu Altus, but exploration offers another way around the castle.'),section('First phase: the chain is longer than it looks','Her two-blade sequences have several branches. Dodge the next attack rather than swinging after the first one. Begin with one light punish after a clear double-thrust finish; add a heavy only when you recognize the recovery.','The summoned glintblades can remain active while she attacks. Track both the floating blades and her body. A distant spell cast can be interrupted by the projectiles even when she seems stationary.'),section('Second phase: three impacts','When the swords gain magic and fire, keep the same restraint and allow room for wider attacks. The twin-moon move drops one moon, then the other, then Rellana herself. Each impact creates a shockwave.','Time separate jumps for the three ground waves rather than jumping once and immediately attacking. Keep stamina available for the sequence. Ensis Wanderer’s Wing Stance is best spent after the chain, not held as she approaches.')],related:['ensis-wanderer','milady','wing-stance','shadow-entry'],sources:[wiki('Rellana'),wiki('Scadutree Fragment')]},
  {...base('messmer','Messmer the Impaler','boss','Shadow Keep','Delayed spear chains, a dangerous grab, and a serpent phase that needs its own rhythm.','boss',true),facts:[['Expansion','Shadow of the Erdtree'],['Location','Dark Chamber · Shadow Keep'],['Preparation','Scadutree Blessing; fire defense'],['Damage choice','Avoid relying on fire']],
    sections:[section('Change a fire-focused loadout','Bring fire protection and activate your available Scadutree Blessing upgrades. Blasphemous Pilgrim should emphasize Lightning Spear or another appropriate non-fire tool here. A fire sword’s usual performance is not evidence that it is the right answer for this boss.'),section('First phase: wait out the spectacle','His opening fire approach and spear strings have delayed parts. Dodge the impact and watch for the next extension. The glowing grab is not safely blocked; prioritize escaping it over taking a trade.','After a completed spear sequence, answer briefly and move. A long spell or stance setup can get caught by a renewed lunge. Healing also needs a genuine recovery, not just several steps of separation.'),section('Second phase: follow the whole serpent sequence','The transformation adds serpent attacks and changes the timing cues. Dodge the bite or slam when it reaches you, then keep watching for additional snakes before attacking the returning humanoid form.','Use a few attempts to identify where he actually returns and pauses. If you consistently die with unused flasks, reduce damage investment in favor of appropriate defense; if you survive but cannot punish, shorten your weapon commitment.')],related:['ensis-wanderer','blasphemous-pilgrim','lightning-spear','shadow-entry','stance-and-survival'],sources:[wiki('Messmer'),wiki('Scadutree Fragment')]},
];

export const blessingSource:Source={label:'Bandai Namco: character progression in Shadow of the Erdtree',url:'https://en.bandainamcoent.eu/elden-ring/news/elden-ring-how-strengthen-your-character-shadow-of-the-erdtree'};
export const guides:RecordNode[]=[
  {...base('first-route','Your first ten hours','guide','Progression','A flexible Limgrave-to-Liurnia route: upgrades and survivability before a final build.','map'),
    sections:[section('1. Make a working character','Meet Melina, receive Torrent, and take the Limgrave map fragment near Gatefront. At the Gatefront ruins, retrieve the Whetstone Knife from the underground chest so you can change supported Ashes of War at a Site of Grace.','Vagabond starts with several equipped armaments and can be in heavy load. Unequip the spare Halberd or another item until the Status screen shows medium load. Every equipped slot counts, including items you are not currently holding.'),section('2. Build a margin for mistakes','Explore Limgrave and the Weeping Peninsula before demanding a win against Margit. Use Golden Seeds for flask charges and Sacred Tears at churches for stronger healing. Spend early levels on Vigor while meeting your chosen weapon’s requirements.','Explore Limgrave Tunnels for Smithing Stones. Choose one main weapon to upgrade rather than dividing the first few tiers between six weapons. A weapon upgrade usually gives an early character a clearer improvement than several damage-stat points.'),section('3. Pick the branch that interests you','Samurai can keep Uchigatana. Bloodhound’s Fang comes from Darriwil in an evergaol. A caster can improve the starting staff and buy Sellen’s spells. These routes work before you can assemble a complete late-game loadout.','The Greatsword detour into Caelid is optional and dangerous. You can take the carriage chest and leave, but you still need its requirements and enough equipment capacity. Avoid interpreting an early pickup as an easy early build.'),section('4. Progress when the setup works','Beat Margit and explore Stormveil when you can survive mistakes and deal consistent damage. Alternatively, the eastern cliff route around Stormveil reaches Liurnia; it does not complete the castle’s quests or rewards for you.','Raya Lucaria and Rennala unlock rebirth. After that, decide whether to keep your first plan or rebuild around a new weapon. The RL150 examples are destinations; early progress is built from the tools actually available.')],related:['margit','rennala','uchigatana','bloodhounds-fang','upgrades-and-rebirth'],sources:[wiki('Whetstone Knife'),wiki('Limgrave Tunnels'),wiki('Vagabond'),wiki('Elden Ring Guide')]},
  {...base('affinities','Ashes, affinities & weapon buffs','guide','Equipment','The skill, scaling and buff eligibility are separate decisions.','sword'),
    facts:[['Heavy','Strength-focused physical scaling'],['Keen','Dexterity-focused physical scaling'],['Magic','Intelligence-based magic damage'],['Flame Art','Faith-based fire damage'],['Occult','Arcane-based physical scaling']],
    sections:[section('Separate three questions','An Ash of War supplies a skill and access to supported affinities. Affinity changes damage types, scaling and sometimes status buildup. A weapon buff adds a temporary effect only if that weapon and affinity allow it. Equipping one does not guarantee the other two.','Normal infusable weapons can usually change skills; fixed-skill Somber weapons usually cannot. Bloodhound’s Fang is an external-buff exception, not an exception that lets you replace its skill.'),section('Use the right whetblade','Iron Whetblade in Stormveil gives broader Heavy, Keen and Quality choices. Glintstone Whetblade in Raya Lucaria supports Magic and Cold. Red-Hot Whetblade in Redmane Castle supports Fire and Flame Art. Black Whetblade in Nokron supports Poison, Blood and Occult.','Compatibility still matters: having every whetblade does not make every affinity available with every Ash. Physical Ashes offer broad choices on compatible weapons. Check the actual selection list when applying the Ash.'),section('Match the build, not the name','Fire and Flame Art are both fire-damage options, but favor different stat plans. Flame Art suits Faith; Fire suits a Strength-oriented plan. Quality expects investment in both Strength and Dexterity and is not automatically better than Heavy or Keen.','Occult supports Arcane-based direct damage. On a weapon with innate bleed, Arcane scaling can also support that buildup. On a weapon without innate bleed, Occult does not simply add hemorrhage. Blood affinity is the option that adds or emphasizes bleed.'),section('Check buff compatibility','Standard, Heavy, Keen and Quality weapons commonly accept greases or weapon-buff spells. Elemental and status affinities generally do not. Fixed unique weapons usually do not accept them either, with documented exceptions such as Bloodhound’s Fang.','Compare actual attack values at your own stats and upgrade tier. Split damage encounters more than one defense calculation, and resistance can change the useful option. This archive does not use a single paper number as a universal ranking.')],related:['uchigatana','greatsword','unsheathe','bloody-slash','wing-stance','dragonblood-duelist'],sources:[wiki('Affinities'),wiki('Black Whetblade'),wiki('Iron Whetblade'),wiki("Bloodhound's Fang")]},
  {...base('stance-and-survival','Roll, recover, break stance','guide','Combat','Equipment load, stamina and stance pressure as one repeatable combat loop.','shield'),
    sections:[section('Start with the load display','Below 30% of maximum equipment load is light load. From 30% to below 70% is medium. At 70% and above, expect heavy load; overloaded equipment prevents normal dodging. Aim for medium while learning and leave a little margin below the threshold.','Weapons, shields, catalysts, armor and talismans in equipped slots count even when you put them away. Inventory weight does not. Raise Endurance or remove equipment when a new item pushes the setup over the threshold.'),section('Do not spend your escape','Use one short punish, then release inputs long enough for stamina to return. Holding a shield slows recovery; lower it when the immediate attack has passed. Green Turtle helps recovery but cannot rescue a fully committed chain.','Guard counters occur with a heavy attack after blocking a hit. Wait for a chain to end, because the counter can be interrupted by the next hit. Blocking grabs, status pressure and elemental damage needs separate caution.'),section('Stance pressure needs consistency','Charged heavies, jump heavies, guard counters and suitable skills can build stance damage. The enemy’s hidden stance recovers after you stop applying pressure, so a single hit followed by a long retreat may not produce a break.','After the break, stop attacking and position for the critical if one is available. A stance break is not the same as bleed, frostbite, a flinch or a guaranteed skip of a scripted phase.'),section('Diagnose the next attempt','If you die during windups, use a shorter punish. If you die after an attack, preserve stamina. If rolling repeats without a hit to dodge, wait for the release cue. If you fail to survive one mistake, review Vigor, armor, relevant defenses and DLC blessing.','Talismans follow the input: Axe supports charged melee heavies, Claw supports ordinary jump attacks, Alexander supports skills. An animation’s appearance does not move it into another bonus category.')],related:['green-turtle','brass-shield','lions-claw','axe-talisman','claw-talisman','margit'],sources:[wiki('Equipment load'),wiki('Stance'),wiki('Green Turtle Talisman'),wiki('Claw Talisman')]},
  {...base('upgrades-and-rebirth','Upgrades, levels & rebirth','guide','Progression','Spend scarce stones on a clear plan, then respec within your class’s real limits.','map'),
    sections:[section('Two upgrade tracks','Normal weapons and catalysts generally use Smithing Stones and reach +25. Somber weapons use Somber Smithing Stones and reach +10. The numbers are different scales: a +10 Somber weapon is fully upgraded, not an unfinished +25 weapon.','Smithing-Stone and Somberstone Miner’s Bell Bearings unlock repeatable purchases of supported stone tiers at the Twin Maiden Husks. The final Ancient Dragon stones remain limited per playthrough, so reserve the last upgrade for a weapon you intend to keep.'),section('Level the requirement, then the character','Meet the weapon or spell requirements first, then raise Vigor and your main damage stat with an eye on upgrades. A staff or seal and a spell have independent requirements. Two-handing multiplies effective Strength for weapon use; it does not multiply Dexterity, Intelligence, Faith or Arcane.','The six sample builds show unbuffed attributes. No Great Rune, talisman, helmet or Physick is hidden in the numbers. Each spread preserves its starting class’s minimum stats and sums to Rune Level 150.'),section('Rebirth has a floor','After defeating Rennala, spend a Larval Tear to redistribute earned levels. You cannot reduce an attribute below your starting class’s base value, and you keep your current level. A Confessor cannot turn its Faith minimum into an Astrologer’s minimum.','If you chose a different class, treat the shown spread as a target role rather than an exact copy. Recalculate the available points instead of assuming the same eight numbers will fit.'),section('A useful order of operations','Choose the weapon and damage type, verify requirements, set Vigor and equipment load, then distribute damage and resource stats. Test the moveset against ordinary enemies before spending a final upgrade stone.','Rebirth does not return Smithing Stones already spent on a weapon. Keep the old weapon as an alternative rather than trying to solve every resistance by rebuilding the entire character.')],related:['rennala','carian-regal-scepter','finger-seal','affinities','first-route'],sources:[wiki('Smithing Stones'),wiki('Somber Smithing Stones'),wiki('Rebirth'),wiki('Origins')]},
  {...base('shadow-entry','Entering the Realm of Shadow','guide','DLC progression','The correct entry bosses, a safe opening route and the blessing that matters inside the expansion.','tree',true),
    sections:[section('The actual entry requirements','Own Shadow of the Erdtree and defeat Starscourge Radahn and Mohg, Lord of Blood in the base game. Approach Miquella’s cocoon in Mohgwyn Palace to enter the Realm of Shadow. Mohg, the Omen in the sewers is not the required boss.','A finished base-game build is helpful, but Rune Level alone does not reproduce the expansion’s progression. Bring upgraded weapons, a medium roll and enough Vigor for mistakes.'),section('Spend fragments, not just runes','Scadutree Fragments increase your Scadutree Blessing when used at a Site of Grace. That blessing supports your damage and damage negation in the Realm of Shadow. Revered Spirit Ashes improve the corresponding blessing for summoned spirits and Torrent.','The blessings are independent and their benefits apply in the expansion area. They do not boost your character’s damage after returning to Limgrave. This guide avoids quoting a fixed damage multiplier chart that could drift with balance changes.'),section('An opening exploration route','Collect the Gravesite Plain map and investigate the nearby ruins and crosses. The Church of Consolation in the southeast has Scadutree Fragments. Activate the blessing before forcing repeated attempts at major bosses.','Explore side paths and check your map; Rellana is not the only route to Scadu Altus. If the castle becomes a wall, return to exploration instead of assuming more Dexterity is the only solution.'),section('Move into the DLC build','Milady and Wing Stance are separate Castle Ensis pickups. Keep your base-game weapon until you find and upgrade the new one. Ensis Wanderer uses no Tarnished Pack equipment, although the current official patch also adds content from that separate pack.','Later exploration and blessing upgrades remain part of progress toward Shadow Keep and Messmer. This launch catalogue is a focused set of routes and encounters, not a complete fragment checklist or DLC completion guide.')],related:['radahn','mohg','ensis-wanderer','milady','rellana','messmer'],sources:[blessingSource,wiki('Scadutree Fragment'),wiki('Mohg, Lord of Blood'),patchSource]},
];

export const allRecords=[...builds,...equipment,...bosses,...guides];
export const byId:Record<string,RecordNode>=Object.fromEntries(allRecords.map(r=>[r.id,r]));
export const recordPath=(r:RecordNode)=>`/${r.kind==='build'?'builds':r.kind==='boss'?'bosses':r.kind==='guide'?'guides':'equipment'}/${r.id}/`;
export const searchable=(r:RecordNode)=>[r.name,r.summary,r.category,...r.tags,...r.sections.flatMap(s=>[s.title,...s.paragraphs]),...r.related.map(id=>byId[id]?.name??''),...(r.build?.loadout.map(l=>`${byId[l.id]?.name} ${l.note}`)??[])].join(' ').toLowerCase();
